# Generated by Django 5.2 on 2025-04-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_s', models.CharField(max_length=225)),
                ('catgory', models.CharField(choices=[('winter', 'شتوي'), ('summer', 'صيفي'), ('m', 'موسمي'), ('flower', 'زهور')], default='m')),
                ('img_s', models.ImageField(blank=True, max_length=255, upload_to='imge')),
            ],
        ),
    ]
