# Generated by Django 5.2 on 2025-04-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myalfajr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeds',
            name='catgory',
            field=models.CharField(choices=[('winter', 'شتوي'), ('summer', 'صيفي'), ('m', 'موسمي'), ('kilo', 'كلوات'), ('flower', 'زهور')], default='m'),
        ),
    ]
