# Generated by Django 5.2 on 2025-04-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myalfajr', '0002_alter_seeds_catgory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seeds',
            name='img_s',
        ),
        migrations.AddField(
            model_name='seeds',
            name='img_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
