# Generated by Django 5.2 on 2025-04-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myalfajr', '0003_remove_seeds_img_s_seeds_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeds',
            name='descript',
            field=models.TextField(blank=True, default=True),
        ),
    ]
