# Generated by Django 5.2 on 2025-04-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myalfajr', '0004_seeds_descript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeds',
            name='descript',
            field=models.TextField(blank=True, default=''),
        ),
    ]
