# Generated by Django 5.2 on 2025-04-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myalfajr', '0005_alter_seeds_descript'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeds',
            name='classification',
            field=models.CharField(blank=True, default=''),
        ),
    ]
